import { useState, useEffect } from 'react';

function App() {
  // --- STATE (Memory) ---
  const [users, setUsers] = useState([]);
  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  
  const [loggedInUser, setLoggedInUser] = useState(null);
  const [habits, setHabits] = useState([]);
  const [newHabitName, setNewHabitName] = useState('');
  
  // NEW: Memory for habits checked off today!
  const [completedHabits, setCompletedHabits] = useState([]);

  // --- GET USERS ---
  const fetchUsers = () => {
    fetch('http://localhost:8080/api/users')
      .then(response => response.json())
      .then(data => setUsers(data))
      .catch(error => console.error("Error fetching data:", error));
  };

  useEffect(() => {
    fetchUsers();
  }, []);

  // --- REGISTER USER ---
  const handleRegister = (e) => {
    e.preventDefault();
    const newUser = { username, email, password };

    fetch('http://localhost:8080/api/users/register', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newUser)
    })
    .then(async response => {
      if (response.ok) {
        setMessage("✅ User registered successfully!");
        setUsername(''); setEmail(''); setPassword('');
        fetchUsers();
      } else {
        const errText = await response.text();
        setMessage("❌ " + errText);
      }
    });
  };

  // --- LOGIN & FETCH HABITS ---
  const handleLogin = (user) => {
    setLoggedInUser(user);
    setCompletedHabits([]); // Reset daily completed list on login

    fetch(`http://localhost:8080/api/habits/user/${user.id}`)
      .then(response => response.json())
      .then(data => setHabits(data))
      .catch(error => console.error("Error fetching habits:", error));
  };

  const handleLogout = () => {
    setLoggedInUser(null);
    setHabits([]);
    setCompletedHabits([]);
  };

  // --- CREATE NEW HABIT ---
  const handleAddHabit = (e) => {
    e.preventDefault();
    const newHabit = { name: newHabitName, userId: loggedInUser.id };

    fetch('http://localhost:8080/api/habits', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newHabit)
    })
    .then(response => response.json())
    .then(data => {
      setHabits([...habits, data]); 
      setNewHabitName(''); 
    });
  };

  // --- NEW: CHECK OFF A HABIT FOR TODAY ---
  const handleCheckOff = (habitId) => {
    const newRecord = { habitId: habitId }; // Date is auto-generated by Java!

    fetch('http://localhost:8080/api/records', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(newRecord)
    })
    .then(response => response.json())
    .then(data => {
      // Add this habit ID to our completed list so the button turns green
      setCompletedHabits([...completedHabits, habitId]);
    })
    .catch(error => console.error("Error checking off habit:", error));
  };

  // --- WHAT THE USER SEES (UI) ---
  return (
    <div style={{ padding: '40px', fontFamily: 'sans-serif', maxWidth: '800px', margin: '0 auto' }}>
      
      {!loggedInUser ? (
        <>
          <h1 style={{ textAlign: 'center', color: '#2c3e50' }}>Momentum Habit Tracker 🚀</h1>
          
          <div style={{ backgroundColor: '#f8f9fa', padding: '20px', borderRadius: '8px', marginBottom: '30px' }}>
            <h2>Create an Account</h2>
            <form onSubmit={handleRegister} style={{ display: 'flex', gap: '10px' }}>
              <input type="text" placeholder="Username" value={username} onChange={(e) => setUsername(e.target.value)} required style={{ padding: '8px', flex: 1 }} />
              <input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} required style={{ padding: '8px', flex: 1 }} />
              <input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} required style={{ padding: '8px', flex: 1 }} />
              <button type="submit" style={{ padding: '8px 16px', backgroundColor: '#3498db', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Register</button>
            </form>
            {message && <p style={{ marginTop: '10px' }}>{message}</p>}
          </div>

          <h2>Who is tracking today? (Click to Login)</h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '15px' }}>
            {users.map(user => (
              <div 
                key={user.id} 
                onClick={() => handleLogin(user)}
                style={{ backgroundColor: '#ecf0f1', padding: '20px', borderRadius: '8px', cursor: 'pointer', textAlign: 'center', border: '2px solid transparent', transition: '0.2s' }}
                onMouseOver={(e) => e.currentTarget.style.borderColor = '#3498db'}
                onMouseOut={(e) => e.currentTarget.style.borderColor = 'transparent'}
              >
                <h3 style={{ margin: 0, color: '#2980b9' }}>{user.username}</h3>
              </div>
            ))}
          </div>
        </>
      ) : (

        <div style={{ backgroundColor: '#ffffff', padding: '30px', borderRadius: '12px', boxShadow: '0 10px 30px rgba(0,0,0,0.1)' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #ecf0f1', paddingBottom: '20px', marginBottom: '20px' }}>
            <h1 style={{ margin: 0, color: '#2c3e50' }}>Welcome, {loggedInUser.username}! 👋</h1>
            <button onClick={handleLogout} style={{ padding: '8px 16px', backgroundColor: '#e74c3c', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Logout</button>
          </div>

          <div style={{ backgroundColor: '#f8f9fa', padding: '20px', borderRadius: '8px', marginBottom: '30px' }}>
            <h3 style={{ marginTop: 0 }}>Start a New Habit</h3>
            <form onSubmit={handleAddHabit} style={{ display: 'flex', gap: '10px' }}>
              <input 
                type="text" 
                placeholder="e.g., Drink 2L of Water, Read 10 Pages..." 
                value={newHabitName}
                onChange={(e) => setNewHabitName(e.target.value)}
                required
                style={{ padding: '12px', flex: 1, borderRadius: '4px', border: '1px solid #ccc', fontSize: '16px' }}
              />
              <button type="submit" style={{ padding: '12px 24px', backgroundColor: '#2ecc71', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '16px', fontWeight: 'bold' }}>
                Add Habit
              </button>
            </form>
          </div>

          <h2>Your Daily Checklist</h2>
          {habits.length === 0 ? (
            <p style={{ color: '#7f8c8d', fontStyle: 'italic' }}>You haven't added any habits yet. Start building momentum above!</p>
          ) : (
            <ul style={{ listStyleType: 'none', padding: 0 }}>
              {habits.map(habit => (
                <li key={habit.id} style={{ backgroundColor: '#ecf0f1', margin: '10px 0', padding: '20px', borderRadius: '8px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: '18px' }}>
                  <strong>{habit.name}</strong>
                  
                  {/* NEW: THE MAGIC BUTTON LOGIC */}
                  {completedHabits.includes(habit.id) ? (
                    <span style={{ color: '#27ae60', fontWeight: 'bold', fontSize: '18px' }}>✅ Done!</span>
                  ) : (
                    <button 
                      onClick={() => handleCheckOff(habit.id)}
                      style={{ padding: '8px 16px', backgroundColor: '#3498db', color: 'white', border: 'none', borderRadius: '20px', cursor: 'pointer', fontWeight: 'bold', transition: '0.2s' }}
                      onMouseOver={(e) => e.currentTarget.style.backgroundColor = '#2980b9'}
                      onMouseOut={(e) => e.currentTarget.style.backgroundColor = '#3498db'}
                    >
                      Complete
                    </button>
                  )}
                  
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}

export default App;